name: test reusable

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app'
        required: false
        type: string
    secrets:
      mang:
        required: true
env:
  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  MANGGILE: ${{ secrets.mang }}

jobs:
  org-secret-call:
    runs-on: ubuntu-latest
    steps:
      - name: Set output repourl
        id: vars
        run: echo "$MANGGILE"
